### ISSUE TITLE
Android S fails

### ISSUE THREAD

**Issue by ElTifo** [kdrag0n/safetynet-fix#21]
Here's the log:

_A/linker_: CANNOT LINK EXECUTABLE "/system/bin/keystore": **cannot locate symbol "_ZN9keymaster19SoftKeymasterDeviceC1Ev" referenced by "/system/bin/keystore"...**

_E/SystemServer_: BOOT FAILURE making Connectivity Service ready
    java.lang.NullPointerException: **Attempt to invoke interface method 'int android.security.keystore.IKeystoreService.exist(java.lang.String, int)' on a null object reference**
        at android.security.KeyStore.contains(KeyStore.java:292)
        at android.security.KeyStore.contains(KeyStore.java:300)

_E/AndroidRuntime_: *** **FATAL EXCEPTION IN SYSTEM PROCESS**: ConnectivityServiceThread
    java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.USER_STARTED flg=0x50000010 (has extras) } in com.android.server.ConnectivityService$3@d80d198
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1635)
        at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$YBWo_pyjHgkQEJgfA2r9yWoWRQA.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: **java.lang.NullPointerException: Attempt to invoke interface method 'int android.security.keystore.IKeystoreService.exist(java.lang.String, int)' on a null object reference**

**Comment by ElTifo** [comment]
You may close this.

shim method works on Andorid S, tested it roght now.
